Minor CheckJNI tweak.
Check for "L;" class names, e.g. "Ljava/lang/String;", in CheckJNI.  If
we see one passed in, give a specific failure message instead of just
allowing the inevitable NoClassDefFoundError to propagate back.

Also, add a message string to the pre-formed NoClassDefFoundError used
by the bootstrap class loader so that it's obvious where it comes from.